<div class="baoliao_art [field:global name=autoindex runphp=yes]@me=((@me-1)?'':'mt20');[/field:global]">
<div class="wx_tit"><img src="/public/images/tx.png">信仰小市民<span>文明规范</span></div>
<div class="bl_con">
	<div class="bl_con_a">
		<a href="[field:arcurl/]"><img src="[field:litpic/]" class="slt"></a>
	</div>
	<div class="bl_con_d">
    <p>[field:title/]</p>
    </div>
	<div class="bl_con_e">
    	<p>[field:description function="cn_substr(@me,60)"/]...</p>
    </div>
    
</div>
</div>