<field:bmjz itemname="报名截止" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:bmjz>
<field:hdsj itemname="活动时间" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hdsj>
<field:hddd itemname="活动地点" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hddd>
<field:jbdw itemname="举办单位" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jbdw>
<field:bmfs itemname="报名方式" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:bmfs>
	<field:cjyq itemname="参加要求" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
	</field:cjyq>
<field:zysx itemname="注意事项" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zysx>
<field:hdzt itemname="活动状态" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="集结中,已结束"  maxlength="250" page="">
</field:hdzt>
