<li>
        	<a href="[field:arcurl/]"><img src="[field:litpic/]" width="640"></a>
        	<div class="wmjjh_r">
            	<h3>[field:title/]</h3>
                <p>[field:hddd/]</p>
                <div class="wmjjh_sj">[field:pubdate function="MyDate('Y-m-d H:i',@me)"/]<span style="color:#33be61">[field:hdzt/]</span></div>
            </div>
            <div class="cl"></div>
        </li>