<div class="baoliao_art [field:global name=autoindex runphp=yes]@me=((@me-1)?'':'mt20');[/field:global]">
<div class="wx_tit_a"><img src="/public/images/tx.png">信仰小市民<span>[field:pubdate function="MyDate('Y-m-d H:i',@me)"/]</span></div>
<div class="bl_con">
	<div class="bl_con_a">
		<img src="[field:litpic/]" class="slt">
	</div>
	<div class="bl_con_d">
    <p>[field:title/]</p>
    </div>
	<div class="bl_con_e">
    	<p>[field:description function="cn_substr(@me,60)"/]...</p>
    </div>
    
</div>
</div>