<field:didian itemname="地点" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:didian>
<field:dqjd itemname="当前进度" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dqjd>
<field:clsx itemname="处理时限" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:clsx>
<field:zrdw itemname="责任单位" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zrdw>
<field:ljys itemname="累计用时" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:ljys>
<field:body itemname="内容" autofield="1" notsend="0" type="textdata" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:body>

<field:slh itemname="受理号" autofield="1" notsend="1" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:slh>

<field:jbdw1 itemname="经办单位1" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jbdw1>

<field:jbdwsj itemname="经办单位1时间" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jbdwsj>

<field:jbdw1yj itemname="经办单位1意见" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jbdw1yj>

<field:jbdw2 itemname="经办单位2" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jbdw2>

<field:jbdw2sj itemname="经办单位2时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jbdw2sj>

<field:jbdw2yj itemname="经办单位2意见" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jbdw2yj>
