<div class="baoliao_list">
	<div class="list_a"><img src="/public/images/[field:global name=autoindex runphp=yes]@me=((@me>2)?'b9':'b6');[/field:global].png"></div>
    <div class="list_b">
    	<a href="[field:arcurl/]"><img src="[field:litpic/]"></a>
    	<div class="tit_a"><a href="[field:arcurl/]">[field:description function='cn_substr(@me,80)'/]...</a></div>
    	<div class="list_c">道路清洁</div>
        <p>[field:add/]</p>
        <p>[field:clsx/]</p>
    </div>
</div>
<div class="cl"></div>