<div class="baoliao_art [field:global name=autoindex runphp=yes]@me=((@me-1)?'':'mt20');[/field:global]">
	<div class="wx_tit"><img src="/public/images/tx.png">信仰小市民<span>摆摊乱占道</span></div>
	<div class="bl_con">
		<div class="bl_con_a">
			<a href="[field:arcurl/]"><img src="/public/images/b5.png" class="slt"></a>
			<p>[field:title/]</p>
		</div>
		<div class="bl_con_b">
		<p>[field:description/]  </p>
		</div>
		<div class="bl_con_c">
			<p>责任单位处理中<span>[field:click/]</span></p>
		</div>
	</div>
	</div>