<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("field","",980,999);
$z[1][4]['name']="title";
$z[2]=Array("field","",1030,1054);
$z[2][4]['name']="shorttitle";
$z[3]=Array("field","",1098,1115);
$z[3][4]['name']="tel";
$z[4]=Array("field","",1117,1134);
$z[4][4]['name']="tel";
$z[5]=Array("arclist","\r\n    	<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n		",1317,1445);
$z[5][4]['typeid']="10";
$z[5][4]['row']="5";
$z[5][4]['titlelen']="100";

?>