<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("field","",506,562);
$z[1][4]['name']="pubdate";
$z[1][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[2]=Array("field","",636,656);
$z[2][4]['name']="litpic";
$z[3]=Array("field","",713,732);
$z[3][4]['name']="title";
$z[4]=Array("field","",761,817);
$z[4][4]['name']="pubdate";
$z[4][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[5]=Array("field","",868,886);
$z[5][4]['name']="body";

?>