<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("field","",917,935);
$z[1][4]['name']="desc";
$z[2]=Array("field","",968,985);
$z[2][4]['name']="add";
$z[3]=Array("field","",1241,1259);
$z[3][4]['name']="dqjd";
$z[4]=Array("field","",1317,1335);
$z[4][4]['name']="clsx";
$z[5]=Array("field","",1386,1404);
$z[5][4]['name']="zrdw";
$z[6]=Array("field","",1455,1473);
$z[6][4]['name']="ljys";
$z[7]=Array("field","",1603,1620);
$z[7][4]['name']="slh";
$z[8]=Array("field","",1770,1788);
$z[8][4]['name']="zrdw";
$z[9]=Array("field","@me = (empty(@me['jbdw1']) ? \"\" : \"<div class='danwei'><img src='/public/images/b3.png'><h3>责任单位处理<span>{@me['jbdwsj']} </span></h3><p>{@me['jbdw1']}</p><p>{@me['jbdw1yj']}</p></div>\"); ",1802,2051);
$z[9][4]['name']="array";
$z[9][4]['runphp']="yes";
$z[10]=Array("field","@me = (empty(@me['jbdw2']) ? \"\" : \"<div class='danwei'><img src='/public/images/b3.png'><h3>责任单位处理<span>{@me['jbdw2sj']}</span></h3><p>{@me['jbdw1']}</p><p>{@me['jbdw2yj']}</p></div>\"); ",2055,2304);
$z[10][4]['name']="array";
$z[10][4]['runphp']="yes";

?>