
    <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='爆料' ischannel='1' link='content_list.php?channelid=17' linkadd='archives_add.php?channelid=17' channelid='17' rank='' target='main' />
  <m:item name='文明集结号' ischannel='1' link='content_list.php?channelid=18' linkadd='archives_add.php?channelid=18' channelid='18' rank='' target='main' />
  <m:item name='问题上诉' ischannel='1' link='content_list.php?channelid=19' linkadd='archives_add.php?channelid=19' channelid='19' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
