<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("arclist","\r\n<div class=\"baoliao_art [field:global name=autoindex runphp=yes]@me=((@me-1)?'mt20':'');[/field:global]\">\r\n<div class=\"wx_tit\"><img src=\"/public/images/tx.png\">信仰小市民<span>文明规范</span></div>\r\n<div class=\"bl_con\">\r\n	<div class=\"bl_con_a\">\r\n		<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" class=\"slt\"></a>\r\n	</div>\r\n	<div class=\"bl_con_d\">\r\n    <p>[field:title/]</p>\r\n    </div>\r\n	<div class=\"bl_con_e\">\r\n    	<p>[field:infolen/]...</p>\r\n    </div>\r\n    \r\n</div>\r\n</div>\r\n",866,1428);
$z[1][4]['row']="100";
$z[1][4]['titlelen']="100";
$z[1][4]['infolen']="60";

?>