<?php
$z[0]=Array("arclist","\r\n<div class=\"baoliao_art [field:global name=autoindex runphp=yes]@me=((@me-1)?'':'mt20');[/field:global]\">\r\n<div class=\"wx_tit\"><img src=\"/public/images/tx.png\">信仰小市民<span>摆摊乱占道</span></div>\r\n<div class=\"bl_con\">\r\n	<div class=\"bl_con_a\">\r\n		<a href=\"[field:arcurl/]\"><img src=\"/public/images/b5.png\" class=\"slt\"></a>\r\n        <p>[field:title/]</p>\r\n	</div>\r\n	<div class=\"bl_con_b\">\r\n    <p>[field:description/]  </p>\r\n    </div>\r\n	<div class=\"bl_con_c\">\r\n    	<p>责任单位处理中<span>[field:click/]</span></p>\r\n    </div>\r\n</div>\r\n</div>\r\n",396,1016);
$z[0][4]['typeid']="3";
$z[0][4]['orderby']="hot";

?>