<?php
$z[0]=Array("field","",64,86);
$z[0][4]['name']="typename";
$z[1]=Array("list","\r\n		<li>\r\n        	<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\"></a>\r\n        	<div class=\"wmjjh_r\">\r\n            	<h3>[field:title/]</h3>\r\n                <p>[field:hddd/]</p>\r\n                <div class=\"wmjjh_sj\">[field:pubdate function=\"MyDate('Y-m-d H:i',@me)\"/]<span style=\"color:#33be61\">[field:hdzt/]</span></div>\r\n            </div>\r\n            <div class=\"cl\"></div>\r\n        </li>\r\n		",817,1281);
$z[1][4]['channelid']="18";
$z[1][4]['addfields']="hddd,hdzt";

?>