<?php
$z[0]=Array("field","",64,86);
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n		<li><a href=\"[field:arcurl/]\">[field:title/]<span>></span></a></li>\r\n		",868,994);
$z[1][4]['row']="100";
$z[1][4]['typeid']="15";
$z[2]=Array("arclist","\r\n		<li><a href=\"[field:arcurl/]\">[field:title/]<span>></span></a></li>\r\n		",1049,1175);
$z[2][4]['row']="100";
$z[2][4]['typeid']="16";
$z[3]=Array("arclist","\r\n		<li><a href=\"[field:arcurl/]\">[field:title/]<span>></span></a></li>\r\n		",1234,1360);
$z[3][4]['row']="100";
$z[3][4]['typeid']="17";

?>