<?php
$z[0]=Array("field","",64,86);
$z[0][4]['name']="typename";
$z[1]=Array("list","\r\n<div class=\"baoliao_art [field:global name=autoindex runphp=yes]@me=((@me-1)?'':'mt20');[/field:global]\">\r\n<div class=\"wx_tit_a\"><img src=\"/public/images/tx.png\">信仰小市民<span>[field:pubdate function=\"MyDate('Y-m-d H:i',@me)\"/]</span></div>\r\n<div class=\"bl_con\">\r\n	<div class=\"bl_con_a\">\r\n		<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" class=\"slt\"></a>\r\n	</div>\r\n	<div class=\"bl_con_d\">\r\n    <p>[field:title/]</p>\r\n    </div>\r\n	<div class=\"bl_con_e\">\r\n    	<p>[field:description function=\"cn_substr(@me,60)\"/]...</p>\r\n    </div>\r\n    \r\n</div>\r\n</div>\r\n",796,1403);
$z[1][4]['pagesize']="100";

?>