<?php
$z[0]=Array("field","",64,86);
$z[0][4]['name']="typename";
$z[1]=Array("list","\r\n<div class=\"baoliao_list\">\r\n	<div class=\"list_a\"><img src=\"/public/images/[field:global name=autoindex runphp=yes]@me=((@me>2)?'b9':'b6');[/field:global].png\"></div>\r\n    <div class=\"list_b\">\r\n    	<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\"></a>\r\n    	<div class=\"tit_a\"><a href=\"[field:arcurl/]\">[field:description function='cn_substr(@me,80)'/]...</a></div>\r\n    	<div class=\"list_c\">道路清洁</div>\r\n        <p>[field:add/]</p>\r\n        <p>[field:clsx/]</p>\r\n    </div>\r\n	<div class=\"cl\"></div>\r\n</div>\r\n",461,1052);
$z[1][4]['pagesize']="20";
$z[1][4]['channelid']="17";
$z[1][4]['addfields']="clsx";

?>