<?php
$z[0]=Array("field","",64,86);
$z[0][4]['name']="typename";
$z[1]=Array("channelartlist","\r\n	<ul id=\"conhbzjtd{dede:global name=itemindex/}\" style=\"display:{dede:global name=itemindex runphp='yes'}@me=((@me-1)?'none':'');{/dede:global};\">\r\n		{dede:arclist row='10'}\r\n		<li><a href=\"[field:arcurl/]\">[field:title/]<span>></span></a></li>\r\n		{/dede:arclist}\r\n    </ul>\r\n	",823,1157);
$z[1][4]['typeid']="12";

?>